### ISSUE TITLE
.relate emits blank line

### ISSUE THREAD

**Issue by cortlandstarrett** [xtuml/pyrsl#20]
I am running into a situation where .relate is adding a blank line to the output buffer.

```
  .if ( te_select_related.by_where )
    .select one where_te_val related by act_sel->ACT_SRW[R664]->V_VAL[R611]->TE_VAL[R2040]
    .relate where_te_val to te_select_related across R2074
    .assign te_select_related.where_clause = where_te_val.buffer
    .assign te_select_related.where_clause_OAL = where_te_val.OAL
  .end if
  .relate te_select_related to te_smt across R2069
  .relate te_select_related to start_te_val across R2070
  .relate te_select_related to start_te_var across R2094
  .relate te_select_related to te_lnk across R2073
```

The above .relate statements end up adding blanks to my output.

I can work around this by adding a .clear statement after the .relate statements.

**Comment by cortlandstarrett** [comment]
I changed the order of instance references in one of the statements, and the bug went away!

```
  .relate te_smt to te_select_related across R2069
  .relate te_select_related to start_te_val across R2070
  .relate te_select_related to start_te_var across R2094
  .relate te_select_related to te_lnk across R2073
```

**Comment by john-tornblom** [comment]
I think this will fix it. I'm currently unable to test it, can you confirm?

pyz file available at: https://ci.appveyor.com/api/buildjobs/7evrfj4wsw13epvc/artifacts/dist%2Fgen_erate.pyz

**Comment by john-tornblom** [comment]
Friendly reminder: is the pyz file available at https://ci.appveyor.com/api/buildjobs/7evrfj4wsw13epvc/artifacts/dist%2Fgen_erate.pyz working as expected?

**Comment by cortlandstarrett** [comment]
No, but I fixed your fix in my fork.
I do not remember why I did not issue a PR.
I will do that now.

**Comment by john-tornblom** [comment]
Hmm. strange, you PR at https://github.com/xtuml/pyrsl/pull/22 contains no semantic changes, you can choose between single quotes or double quotes in python. I suspect you forgot to regenerate the parse tables. In any case, it works no so I'll close this issue.

**Comment by cortlandstarrett** [comment]
The passage of time attenuates my memory!
Thanks.
